#!/bin/sh

user=empfs
home=/var/empfs
group=fuse

echo "removing artefacts for empfs @VERSION@..."

echo "\t1. deleting user $user"
grep "^$user:" /etc/passwd 1>/dev/null 2>&1
if [ $? -eq 0 ]
then
	userdel $user
fi

echo "\t2. not deleting group $group"

echo "\t3. deleting home $user directory $home"
rm -rf $home

echo "removed."

